name: App Deploy

on:
  pull_request:
    types:
      - labeled
      - synchronize  # re-run on new commits if label already present

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'app:compooss')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add your deployment/build steps here
      - name: Run deploy
        run: echo "Running workflow for compooss app"
